algorithm: ours
save_dir: ./saved_models/ours/
save_name: cifar_50_50_estimatek
resume: False
load_path: ./saved_models/UNO/UNO_cifar100_50_100_Ours_w/latest_model.pth
num_outer_iters: 10
lr_w: 0.1
confidence: 0
set_imb: 1
lab_imbalance_factor: 50
imbalance_factor: 50
gamma: 500
overwrite: True
max_epochs: 50
batch_size: 128
num_labeled_classes: 50
num_unlabeled_classes: 50
lr: 0.001
min_lr: 0.0001
warmup_epochs: 3
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
net: vit_base_patch16_224
net_from_name: False
data_dir: ./data
dataset: CIFAR100
num_classes: 100
regenerate: True
ratio: 50
num_workers: 4
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
use_pretrain: True
gpu: "0"
pretrain_path: /public/home/zhangchy2/workdir/pretrained/dino/dino_vitbase16_pretrain.pth
cosine_classifier: 4
num_iters_sk: 3
epsilon_sk: 0.05
temperature: 0.1
random_head: True
flag: 0
val: False
logit_adj_post: True
crt: False
# representation_path: saved_models/ours/cifar_50_50_estimatek/latest_model.pth
representation_path: /public/home/xurj/my/ViT_NCD/saved_models/UNO/cifar_50_100_cos_pretrain/latest_model.pth
est_k: True
error: -30
