algorithm: ours
save_dir: ./saved_models/ours/
save_name: herb_001
num_outer_iters: 10
lr_w: 0.1
gamma: 500
resume: False
load_path: 
overwrite: True
max_epochs: 70
batch_size: 128
num_labeled_classes: 342
num_unlabeled_classes: 341
lr: 1e-3
min_lr: 1e-4
warmup_epochs: 5
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0001
net: vit_base_patch16_224
net_from_name: False
data_dir: ./data
dataset: herbarium_19
regenerate: True
ratio: 50
num_workers: 12
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
use_pretrain: True
gpu: 0
pretrain_path: /public/home/zhangchy2/workdir/pretrained/dino/dino_vitbase16_pretrain.pth
num_iters_sk: 3
epsilon_sk: 0.01
temperature: 0.1
random_head: True
flag: 0
num_classes: 683
logit_adj_post: True
representation_path: 
est_k: False
# error: -188