algorithm: ours
save_dir: ./saved_models/ours/
save_name: img_50_100_estimatek
num_outer_iters: 50
lr_w: 0.1
confidence: 0
set_imb: 1
lab_imbalance_factor: 50
imbalance_factor: 100
gamma: 500
resume: False
load_path: ./saved_models/UNO//UNO_image100_50_50_100_1_memory/latest_model.pth
overwrite: True
max_epochs: 50
batch_size: 128
num_labeled_classes: 50
num_unlabeled_classes: 50
lr: 5e-4
min_lr: 1e-4
warmup_epochs: 5
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0001
net: vit_base_patch16_224
net_from_name: False
data_dir: ./data
dataset: ImageNet100
num_classes: 100
regenerate: False
ratio: 50
num_workers: 4
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
use_pretrain: True
gpu: 0
pretrain_path: /public/home/zhangchy2/workdir/pretrained/dino/dino_vitbase16_pretrain.pth
topk: 5
cosine_classifier: 4
num_iters_sk: 3
epsilon_sk: 0.05
temperature: 0.1
random_head: True
flag: 0
val: False
logit_adj_post: True
crt: False
est_k: True
error: 9
representation_path: saved_models/ours/img_50_100_estimatek/latest_model.pth



