algorithm: ours
save_dir: ./saved_models/ours/
save_name: inaturalist18
num_outer_iters: 10
lr_w: 0.1
confidence: 0
set_imb: 1
gamma: 500
resume: False
load_path: ./saved_models/UNO/UNO_herbarium_19_ETF_seed1/latest_model.pth
overwrite: True
max_epochs: 70
batch_size: 128
num_labeled_classes: 500
num_unlabeled_classes: 500
lr: 1e-3
min_lr: 1e-4
warmup_epochs: 5
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0001
net: vit_base_patch16_224
net_from_name: False
data_dir: ./data
dataset: inaturalist18
regenerate: True
ratio: 50
num_workers: 12
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
use_pretrain: True
gpu: 0
pretrain_path: /public/home/zhangchy2/workdir/pretrained/dino/dino_vitbase16_pretrain.pth
topk: 5
cosine_classifier: 4
num_iters_sk: 3
epsilon_sk: 0.01
temperature: 0.1
random_head: True
flag: 0
num_classes: 1000
logit_adj_post: True
representation_path: saved_models/ours/inaturalist18/best_model.pth
est_k: False
crt: False
max_classes: 2000
alpha: 1